#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : nfs4-acl-tools
Version  : 0.3.5
Release  : 2
URL      : http://linux-nfs.org/~bfields/nfs4-acl-tools/nfs4-acl-tools-0.3.5.tar.gz
Source0  : http://linux-nfs.org/~bfields/nfs4-acl-tools/nfs4-acl-tools-0.3.5.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0 LGPL-2.1
Requires: nfs4-acl-tools-bin = %{version}-%{release}
Requires: nfs4-acl-tools-license = %{version}-%{release}
Requires: nfs4-acl-tools-man = %{version}-%{release}
BuildRequires : attr-dev

%description
This package contains commandline ACL utilities for the Linux NFSv4
client.
See INSTALL for instructions.

%package bin
Summary: bin components for the nfs4-acl-tools package.
Group: Binaries
Requires: nfs4-acl-tools-license = %{version}-%{release}

%description bin
bin components for the nfs4-acl-tools package.


%package license
Summary: license components for the nfs4-acl-tools package.
Group: Default

%description license
license components for the nfs4-acl-tools package.


%package man
Summary: man components for the nfs4-acl-tools package.
Group: Default

%description man
man components for the nfs4-acl-tools package.


%prep
%setup -q -n nfs4-acl-tools-0.3.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1551224754
export LDFLAGS="${LDFLAGS} -fno-lto"
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1551224754
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/nfs4-acl-tools
cp COPYING %{buildroot}/usr/share/package-licenses/nfs4-acl-tools/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/nfs4_editfacl
/usr/bin/nfs4_getfacl
/usr/bin/nfs4_setfacl

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/nfs4-acl-tools/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/nfs4_editfacl.1
/usr/share/man/man1/nfs4_getfacl.1
/usr/share/man/man1/nfs4_setfacl.1
/usr/share/man/man5/nfs4_acl.5
